void timer_init();
char checkdigit(int i);
void startgame();
void display_update();
void display_image(int x, const uint8_t *data); 
void display_string(int line, char *s);
uint8_t spi_send_recv(uint8_t data); 
void delay(int cyc); 
void startmenu();
int choosename();
void highscore();
int getbtn(int nr);
void light_led(int nr);
void shut_led(int nr);
void play();
void stringPrinter();
void setFirst(char player[6], int score);
void setSecond(char player[6], int score);
void setThird(char player[6], int score);
void resetCurrentPlayer();
void intToString(int value, char *s);
